language: node_js
node_js:
  - '0.10'
  - '0.12'
  - '4'
before_install:
  - 'npm -g install npm@latest-2 && npm install codeclimate-test-reporter -g'
addons:
  code_climate:
    repo_token: c8ea2e0ac816cb09d3c8a2bdf92394f81908dcbe858ec70fd1bcbac2c8cfb030
after_script:
  - 'npm run gen-coverage && cat coverage/lcov.info | codeclimate-test-reporter'
notifications:
  slack:
    secure: PGdsKStC7uOM9LRZzXun/z5IQqhV39/agmi8Bpqa04NqcS6kdKkRrKyhPvw49MX9FspzqklUjJfhYQBJ5WEXUqUc7VFl4xT7TaKmujDMeH4w6DzpesV17iM4ydklpbxcw7VOjIPckXOI3FWQlXbSDmgrAk997VBDGzg3qSOYBQQ=
